// Auto-generated by scripts/update-domains.js
import domainList from './disposable-domains.json';

// Convert to Set for O(1) lookups
export const DISPOSABLE_DOMAINS = new Set(domainList);

export const getLastUpdated = () => "2026-03-30T02:41:28.019Z";
