const fs = require('fs');
const path = require('path');

// Sources for disposable domains
const SOURCES = [
  'https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.json',
  'https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json',
  'https://raw.githubusercontent.com/groundcat/disposable-email-domain-list/master/domains.json'
];

async function updateDomains() {
  console.log('🔄 Starting domain list update...');
  const allDomains = new Set();

  // 1. Fetch from sources
  for (const url of SOURCES) {
    try {
      console.log(`fetching from ${url}...`);
      const response = await fetch(url);
      if (!response.ok) throw new Error(`Failed to fetch ${url}`);
      const data = await response.json();
      
      if (Array.isArray(data)) {
        data.forEach(d => allDomains.add(d.toLowerCase().trim()));
      }
    } catch (err) {
      console.error(`❌ Error fetching source: ${err.message}`);
    }
  }

  // 2. Add our manual overrides (important ones that might be missed)
  const manualDomains = [
    "temp-mail.org", "10minutemail.com", "guerrillamail.com", "yopmail.com",
    "sharklasers.com", "mailinator.com", "getnada.com", "dispostable.com"
  ];
  manualDomains.forEach(d => allDomains.add(d));

  // 3. Convert to sorted array
  const sortedDomains = Array.from(allDomains).sort();
  
  console.log(`✅ Collected ${sortedDomains.length} unique disposable domains.`);

  // 4. Write to JSON file
  const outputPath = path.join(__dirname, '../lib/disposable-domains.json');
  fs.writeFileSync(outputPath, JSON.stringify(sortedDomains, null, 2));
  console.log(`💾 Saved to ${outputPath}`);

  // 5. Update the TS helper file
  const tsPath = path.join(__dirname, '../lib/domains.ts');
  const tsContent = `// Auto-generated by scripts/update-domains.js
import domainList from './disposable-domains.json';

// Convert to Set for O(1) lookups
export const DISPOSABLE_DOMAINS = new Set(domainList);

export const getLastUpdated = () => "${new Date().toISOString()}";
`;
  fs.writeFileSync(tsPath, tsContent);
  console.log(`💾 Updated ${tsPath}`);
}

updateDomains();
